config/routes.rb
Rails.application.routes.draw do

  
  root 'pages#home'
  get 'about', to: 'pages#about'
  
  resources :articles do
    resources :comments
  end
  
  get 'signup', to: 'users#new'
  resources :users, except: [:new]
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  resources :categories, except: [:destroy]

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article
  belongs_to :user
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  
  before_action :find_article
  before_action :login_to_comment, only: [:create]
  before_action :find_comment, only: [:destroy, :edit, :update, :require_same_user_comments]
  before_action :require_same_user_comments, only: [:destroy, :edit, :update]
  
  
  def create
    @comment = @article.comments.create(params[:comment].permit(:content))
    @comment.user_id = current_user.id
    @comment.save
    
    if @comment.save
      redirect_to article_path(@article)
    else
      render 'edit'
    end
  end
  
  def edit
    
  end
  
  
  def update
    if @comment.update(params[:comment].permit(:content))
      redirect_to article_path(@article)
    else
      render 'new'
    end
  end
  
  def destroy
    @comment.destroy
    redirect_to article_path(@article)
  end
  
  private
  
  def find_article
    @article = Article.find(params[:article_id])
  end
  
  def find_comment
    @comment = @article.comments.find(params[:id])
  end
  
  def require_same_user_comments
      if current_user.id != @comment.user_id and !current_user.admin?
        flash[:danger] = "You do not have authorization to do that"
        redirect_to article_path(@article)
      end
  end
  
  def login_to_comment
    if current_user == nil
      flash[:danger] = "You must be logged in to comment"
      redirect_to article_path(@article)
    end
  end
  
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<% @comments.each do |comment| %>
  <hr />
  <strong><%= link_to comment.user.username, users_path(current_user) %></strong>:
  <br />
  <%= comment.content %>
  <br /><br />
  <% if logged_in? && (current_user == comment.user || current_user.admin?) %>
    <%= link_to "Edit", edit_article_comment_path(comment.article, comment), class: "btn btn-xs btn-primary" %>
    <%= link_to "Delete", [comment.article, comment], method: :delete, class: "btn btn-xs btn-danger" %>
  <% end %>
  <div align="right" class="time-format">
    <%= comment.created_at.strftime("%H:%M-%a-%m-%Y") %>
  </div>  
<% end %>

<%= render 'comments/form' %>

app/views/comments/_form.html.erb
<hr />
<div align="right">
  <%= form_for([@article, @article.comments.build]) do |f| %>
    <%= f.text_field :content, style: "width: 250px;", placeholder: "Leave a comment...", autofocus: true %>
    <%= f.submit "Post", class: "btn btn-xs btn-primary" %>
  <% end %>
</div>

app/views/comments/edit.html.erb
<div class="page-title">
  <h1>Edit comment</h1>
</div>
<hr />

<div align="left">
  <%= form_for([@article, @comment]) do |f| %>
    <%= f.text_field :content, style: "width: 250px;", placeholder: "Leave a comment...", autofocus: true %>
    <%= f.submit "Post", class: "btn btn-xs btn-primary" %>
  <% end %>
</div>
<hr />
<div class="col-xs-4 col-xs-offset-3">
  [ <b><%= link_to "Cancel request and return to the article", article_path(@article) %></b> ]
</div>