config/routes.rb
Rails.application.routes.draw do

  
  root 'pages#home'
  get 'about', to: 'pages#about'
  
  resources :articles do
    resources :comments
  end
  
  get 'signup', to: 'users#new'
  resources :users, except: [:new]
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  resources :categories, except: [:destroy]

end

app/models/article.rb
class Article < ActiveRecord::Base
  
  #setting up the one to many relation of articles table with user table
  belongs_to :user
  #setting up the many to many relation of articles table with article_categories table
  has_many :article_categories
  has_many :categories, through: :article_categories
  has_many :comments, dependent: :destroy
  
  validates :title, presence: true, length: { minimum: 5, maximum: 25 }
  validates :description, presence: true, length: { minimum: 15, maximum: 300 }
  validates :user_id, presence: true
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  
  #use the method :set_article from private only on those methods before they do anything else 
  # they always execute in order
  before_action :set_article, only: [:edit, :update, :show, :destroy]
  #this is to prevent someone to access edit articles if he's not logged in like from url
  before_action :require_user, except: [:index, :show]
  #prevent user to modify other users articles
  before_action :require_same_user, only: [:edit, :update, :destroy]
  
  #for the page with all the articles
  def index
    #new variable for all the articles
    @articles = Article.paginate(page: params[:page], per_page: 6)
  end
  
  #create new article
  def new
    @article = Article.new
  end
  
  #edit existing article
  def edit
    #@article = Article.find(params[:id])
  end
  
  #create the new article and saving it to the db
  def create
    
    @article = Article.new(article_params)
    @article.user = current_user
    if @article.save
      #render plain: params[:article].inspect
      #flash[:notice] to create an informational message for the user 
      #it will be displayed on every page using the html wrapper in views/layouts/application.html.erb
      flash[:success] = "Article was succesfully created."
      redirect_to article_path(@article)
    else
      #renders a new article.new page
      render 'new'
    end
    
  end
  
  #update the existing article from edit and save it to the db
  def update
    #@article = Article.find(params[:id])
    if @article.update(article_params)
      flash[:success] = "Articlae succesfully updated."
      redirect_to article_path(@article)
    else
      render 'edit'
    end
  end
  
  #show the current article on the web app
  def show
    #@article = Article.find(params[:id])
    @comments = Comment.where(article_id: @article).order("created_at DESC")
  end
  
  #deletes the current article
  def destroy
    #@article = Article.find(params[:id])
    @article.destroy
    
    redirect_to articles_path
    flash[:danger] = "Article was deleted."
  end
  
  
  private
    
    def set_article
      @article = Article.find(params[:id])
    end
    #private function the gives the params needed to identify the article we want to edit or create
    #category_ids will add the relation between the categories selectd and article_id 
    def article_params
     params.require(:article).permit(:title, :description, category_ids: [])
    end
    
    #prevent user to modify other users articles
    def require_same_user
      if current_user != @article.user and !current_user.admin?
        flash[:danger] = "You do not have authorization to do that"
        redirect_to root_path
      end
    end
  
end

app/views/articles/_article.html.erb
<div class="row">
  <% obj.each do |article| %>
    <div class="col-xs-6 col-xs-offset-0" >
      <div class="well well-lg">
        <div class="article-title">
          <%= link_to article.title, article_path(article) %>
        </div>
        <div class="article-body">
          <%= truncate(article.description, length: 100) %>
            <div class="article-meta-details">
              <small><b>Created by: <%= link_to article.user.username, user_path(article.user) if article.user  %>,
                <%= time_ago_in_words(article.created_at) %> ago,
                last updated: <%= time_ago_in_words(article.updated_at) %> ago
              </small>
              <small class="number-comments">
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                <%= link_to(pluralize(article.comments.count, "comment"), article_path(article)) %>
              </small>
            </div>
        </div>
         <% if article.categories.any? %>
          <p>Categories: <%= render article.categories %></p>
         <% end %>
        <% if logged_in? && (current_user == article.user || current_user.admin?) %>
          <div class="article-actions">
            <%= link_to "Edit article", edit_article_path(article), class: "btn btn-xs btn-primary" %>
            <%= link_to "Delete this article", article_path(article), method: :delete, 
              data: { confirm: "Are you sure you want to delete this article?" }, class: "btn btn-xs btn-danger" %>
          </div>
        <% end %>
      </div>
    </div>
  <% end %>  
</div>

app/views/articles/_form.html.erb
<!-- loading _errors.html.erb and declaring the generiv var obj as an @article -->
<%= render 'shared/errors', obj: @article %>
<div class="row">
  <div class="col-xs-12">

    <%= form_for(@article, :html => {class: "form-horizontal", role: "form"}) do |f| %>
    
      <div class="form-group">
        <div class="control-label col-sm-1">
          <%= f.label :title %>
        </div>
        
        <div class="col-sm-6">
          <%= f.text_field :title, class: "form-control", placeholder: "Title of article:", autofocus: true %>
        </div>
      </div>

      <div class="form-group">
        <div class="control-label col-sm-1">
          <%= f.label :description %>
        </div>
        
        <div class="col-sm-8">
          <%= f.text_area :description, class: "form-control", rows: 10,  placeholder: "Body of article: " %>
        </div>
      </div>
      
      <div class="form-group">
        <div class="row">
          <div class="col-sm-offset-1 col-sm-8 checkbox-layout" align="center">
            <!-- adding category checkboxes to put the article in any category desired  -->
            <%= f.collection_check_boxes :category_ids, Category.all, :id, :name do |cb| %>
              <% cb.label(class: "checkbox-inline input_checkbox") {cb.check_box(class: "checkbox") + cb.text} %>
            <% end %>
          </div>
        </div>
      </div>

      <div class="form-group">
        <div class="col-sm-offset-1 col-sm-10">
          <%= f.submit class: "btn btn-primary btn-lg" %>
        </div>
      </div>

    <% end %>
    
    <div class="col-xs-4 col-xs-offset-3">
      [ <b><%= link_to "Cancel request and return to articles listing", articles_path %></b> ]
    </div>
  </div>
</div>

<div class="footer-space">&nbsp;<br />&nbsp;<br />&nbsp;</div>

app/views/articles/edit.html.erb
<div class="page-title">
  <h1>Edit existing article</h1>
</div>
<br />

<!-- render the _form.html.erb file which is called a partial --> 
<%= render 'form' %>

app/views/articles/index.html.erb
<div class="page-title">
  <h1>Listing all articles</h1>
</div>
<hr />

<div>
  <%= will_paginate @collection, renderer: BootstrapPagination::Rails %>
</div>


<%= render 'article', obj: @articles %>

<div align="center">
  <%= will_paginate @collection, renderer: BootstrapPagination::Rails  %>
</div>

<div class="footer-space">&nbsp;<br />&nbsp;<br />&nbsp;</div>

app/views/articles/new.html.erb
<div class="page-title">
  <h1>Create an article</h1>
</div>
<br />

<!-- render the _form.html.erb file which is called a partial -->
<%= render 'form' %>

app/views/articles/show.html.erb
<div class="page-title">
  <h1><%= @article.title %></h1>
</div>
<hr />
<br />
<div class="row">
  <div class="well col-xs-8 col-xs-offset-0">
    <ul class="listing">
      <div class="row center">
        <div class="col-md-6 col-md-offset-3">
          <li>Created by:</li>
          <li><%= link_to profile_pic(@article.user), user_path(@article.user) %></li>
          <li class="article-title">
            <%= link_to @article.user.username, user_path(@article.user) %>
          </li>
          <li><small><%= pluralize(@article.user.articles.count, "article") if @article.user.articles  %></small></li>
          <li><h4><strong>Description</strong></h4></li>
        </div>
      </div>  
    </ul>    
  
      <%= simple_format(@article.description) %>
      <% if @article.categories.any? %>
        <p>Categories: <%= render @article.categories %></p>
      <% end %>
      <br />
      <div class="article-actions">
        <% if logged_in? && (current_user == @article.user || current_user.admin?) %>
          <%= link_to "Edit article", edit_article_path(@article), class: "btn btn-xs btn-primary" %>
          <%= link_to "Delete this article", article_path(@article), method: :delete, 
            data: { confirm: "Are you sure you want to delete this article?" }, class: "btn btn-xs btn-danger" %>
        <% end %>
        <%= link_to "View all articles", articles_path, class: "btn btn-xs btn-success" %>
      </div>
      <hr /><hr />
      <div class="comment-section">Comments:</div>
      <%= render 'comments/comment' %>
  </div>
</div>

<div class="footer-space">&nbsp;<br />&nbsp;<br />&nbsp;</div>