config/routes.rb
Rails.application.routes.draw do

  
  root 'pages#home'
  get 'about', to: 'pages#about'
  
  resources :articles do
    resources :comments
  end
  
  get 'signup', to: 'users#new'
  resources :users, except: [:new]
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  resources :categories, except: [:destroy]

end

app/models/category.rb
class Category < ActiveRecord::Base
  
  #setting up the many to many relation of category table with article_categories table
  has_many :article_categories
  has_many :articles, through: :article_categories
  
  validates :name, presence: true, length: { minimum: 4, maximum: 25  }
  validates_uniqueness_of :name
  
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  
  before_action :require_admin, except: [:index, :show]
  
  #each def variable will be accesible from the view with the same name!!!
  #@category from def new will not be visible in show!!! 
  #it has to be defined in show too to be visible in the show view
  def new
    @category = Category.new
  end
  
  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:success] = "Category was created succesfully"
      redirect_to categories_path
    else 
      render 'new'
    end
  end
  
  def edit
    @category = Category.find(params[:id])
  end
  
  def update
    @category = Category.find(params[:id])
    if @category.update(category_params)
      flash[:success] = "Category name was succesfully updated"
      redirect_to category_path(@category)
    else
      render 'edit'
    end
  end
  
  def index
    @categories = Category.paginate(page: params[:page], per_page: 8)
  end
  
  def show
    @category = Category.find(params[:id])
    @category_articles = @category.articles.paginate(page: params[:page], per_page: 6)
  end
  
  
  private
  
  def category_params
    params.require(:category).permit(:name)
  end
  
  def require_admin
    if !logged_in? || (logged_in? and !current_user.admin?)
      flash[:danger] = "Only admins can perform that action"
      redirect_to categories_path
    end
  end
  
end

app/views/categories/_category.html.erb
<span class="badge">
  <%= link_to category.name, category_path(category) %>
</span>
&nbsp;&nbsp;&nbsp;

app/views/categories/_cform.html.erb
<%= render 'shared/errors', obj: @category %>

<%= form_for(@category, :html => {multipart: true, class: "form-horizontal", role: "form"}) do |f| %>

  <div class="form-group">
    <div class="control-label col-sm-1">
      <%= f.label :name %>
    </div>
    
    <div class="col-sm-6">
      <%= f.text_field :name, class: "form-control", placeholder: "Enter category name", autofocus: true %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-sm-offset-1 col-sm-10">
      <%= f.submit class: "btn btn-primary btn-lg" %>
    </div>
  </div>

<% end %>

<div class="col-xs-4 col-xs-offset-3">
  [ <b><%= link_to "Cancel request and return to welcome page", root_path %></b> ]
</div>

app/views/categories/edit.html.erb
<div class="page-title">
  <h1>Update Category</h1>
</div>
<hr />

<%= render 'cform' %>

app/views/categories/index.html.erb
<div class="page-title">
  <h1>Categories</h1>
</div>
<hr />

<div align="center">
  <%= will_paginate @collection, renderer: BootstrapPagination::Rails %>
</div>

 <ul class="listing">
  <div class="row">
    <% @categories.each do |category| %>
      <div class="well col-md-5 col-md-offset-1">
        <li class="article-title">
          <%= link_to "#{category.name}", category_path(category) %>
        </li>
        <li><small><%= pluralize(category.articles.count, "article") %></small></li>
      </div>
    <% end %>
  </div>
</ul>

    
<div align="center">
  <%= will_paginate @collection, renderer: BootstrapPagination::Rails %>
</div>

<div class="footer-space">&nbsp;<br />&nbsp;<br />&nbsp;</div>

app/views/categories/new.html.erb
<div class="page-title">
  <h1>New Category</h1>
</div>
<hr />
<%= render 'shared/errors', obj: @category %>


<%= form_for(@category, :html => {multipart: true, class: "form-horizontal", role: "form"}) do |f| %>

  <div class="form-group">
    <div class="control-label col-sm-1">
      <%= f.label :name %>
    </div>
    
    <div class="col-sm-6">
      <%= f.text_field :name, class: "form-control", placeholder: "Enter category name", autofocus: true %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-sm-offset-1 col-sm-10">
      <%= f.submit class: "btn btn-primary btn-lg" %>
    </div>
  </div>

<% end %>

<div class="col-xs-4 col-xs-offset-3">
  [ <b><%= link_to "Cancel request and return to welcome page", root_path %></b> ]
</div>

app/views/categories/show.html.erb
<div class="page-title">
  <h1><%= "#{@category.name}" %> Category</h1>
</div>
<% if logged_in? and current_user.admin? %>
<div class="row edit-category">
  <span class="badge"><%= link_to "Edit category name", edit_category_path(@category) %></span>
</div>
<% end %>

<hr />

<div align="center">
  <%= will_paginate @category_articles, renderer: BootstrapPagination::Rails %>
</div>

<%= render 'articles/article', obj: @category_articles %>

<div align="center">
  <%= will_paginate @category_articles, renderer: BootstrapPagination::Rails %>
</div>